version: '2'
services:
  postgres:
    image: postgres:11.5
    restart: always
    env_file:
      - ./development.env
    volumes:
      - ../tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
